apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: kafka-cluster-producer-tests
  labels:
    app: mesosphere-load-tests
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: mesosphere-load-tests
    spec:
      containers:
      - name: kafka-ultron-loader
        image: zmalikshxil/kafka-ultron:0.0.1-alpha
        imagePullPolicy: Always
        command:
        - /opt/kafka/run_producer_test.sh
        env:
        - name: BOOTSTRAP_SERVERS
          value: "kafka-svc.kudo-kafka.svc.cluster.local:9093"
        - name: NUM_TOPICS
          value: "30"
        - name: TEST_INTERVAL_SECONDS
          value: "1"
        - name: PRODUCER_THROUGHPUT
          value: "100"
        - name: NUM_RECORDS
          value: "100"
        - name: RECORD_SIZE
          value: "100"
        livenessProbe:
          exec:
            command:
            - ps -ef | grep run_producer_test.sh
          initialDelaySeconds: 10
          periodSeconds: 30
        readinessProbe:
          exec:
            command:
            - ps -ef | grep run_producer_test.sh
          initialDelaySeconds: 10
          periodSeconds: 30
        resources:
          limits:
            cpu: 100m
            memory: 512Mi
          requests:
            cpu: 100m
            memory: 512Mi
  strategy:
    type: Recreate
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: kafka-cluster-consumer-tests
  labels:
    app: mesosphere-load-tests
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: mesosphere-load-tests
    spec:
      containers:
      - name: kafka-ultron-loader
        image: zmalikshxil/kafka-ultron:0.0.1-alpha
        imagePullPolicy: Always
        command:
        - /opt/kafka/run_consumer_test.sh
        env:
        - name: BOOTSTRAP_SERVERS
          value: "kafka-svc.kudo-kafka.svc.cluster.local:9093"
        - name: NUM_TOPICS
          value: "30"
        - name: NUM_RECORDS
          value: "100"
        - name: TEST_INTERVAL_SECONDS
          value: "1"
        livenessProbe:
          exec:
            command:
            - ps -ef | grep run_producer_test.sh
          initialDelaySeconds: 10
          periodSeconds: 30
        readinessProbe:
          exec:
            command:
            - ps -ef | grep run_producer_test.sh
          initialDelaySeconds: 10
          periodSeconds: 30
        resources:
          limits:
            cpu: 100m
            memory: 512Mi
          requests:
            cpu: 100m
            memory: 512Mi
  strategy:
    type: Recreate
